sudo: required
language: generic
branches:
  only:
    - section8
services:
  - docker
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jeensh/docker-react-app -f section7-8/dockerfile.dev section7-8/
script:
  - docker run -e CI=true jeensh/docker-react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-751154654103"
  bucket_path: "doker-react-app"
  on:
    branch: section8
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY